### ISSUE TITLE
I can't see the flow chart

### ISSUE THREAD

**Issue by mocha666** [BG-Software-LLC/SSBBungeeBridge#1]
I can't see the flow chart

**Comment by OmerBenGera** [comment]
Even after signing up?

**Comment by OmerBenGera** [comment]
nvm, right - seems like an issue with permissions and this website requires me to purchase access for it.
I will look into a different service and update the flowchart.

**Comment by mocha666** [comment]
Can this project be put into production environment??

**Comment by OmerBenGera** [comment]
> Can this project be put into production environment??

I dont understand what you mean by that?

**Comment by mocha666** [comment]
> I dont understand what you mean by that?

Oh, well, I have some incorrect understanding of the terms in development. When I was studying, I understood that the environment that officially provides external services is called the production environment, and the local machine used for development is called the development environment.

Can this project run stably on an official server?

**Comment by OmerBenGera** [comment]
> > I dont understand what you mean by that?
> 
> Oh, well, I have some incorrect understanding of the terms in development. When I was studying, I understood that the environment that officially provides external services is called the production environment, and the local machine used for development is called the development environment.
> 
> Can this project run stably on an official server?

Ah I understand what you meant before.
Sadly not, this product is still in development and is not ready to be ran on a server

**Comment by mocha666** [comment]
> Ah I understand what you meant before. Sadly not, this product is still in development and is not ready to be ran on a server

Ah ok, i still want to see the **flow chart**
